
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name:  Spring-Authenticationdemo

role:
  admin: ADMIN
  user: USER
